export const news = [
    {
        title: "GNJR participa en mesa de trabajo con INDAP sobre políticas de juventud rural",
        excerpt: "Representantes del gremio se reunieron con autoridades de INDAP para discutir nuevos instrumentos de fomento productivo dirigidos específicamente a jóvenes agricultores.",
        date: "15 Dic 2024",
        location: "Santiago",
        category: "Políticas Públicas",
        image: "/placeholder.svg?height=300&width=500",
    },
    {
        title: "Lanzamiento exitoso de AgroDigitalIA en región de Valparaíso",
        excerpt: "Más de 40 jóvenes agricultores participaron en el lanzamiento del programa de transformación digital para el agro en la región de Valparaíso.",
        date: "10 Dic 2024",
        location: "Valparaíso",
        category: "Programas",
        image: "/placeholder.svg?height=300&width=500",
    },
    {
        title: "Taller de liderazgo rural convoca a más de 50 jóvenes en Concepción",
        excerpt: "La Escuela de Liderazgo Rural del GNJR realizó su primer taller en la región del Biobío con gran convocatoria y participación activa.",
        date: "5 Dic 2024",
        location: "Concepción",
        category: "Capacitación",
        image: "/placeholder.svg?height=300&width=500",
    },
    {
        title: "GNJR firma convenio de colaboración con la Universidad de Chile",
        excerpt: "El gremio establece alianza estratégica con la Facultad de Ciencias Agronómicas para desarrollar programas de extensión e investigación.",
        date: "1 Dic 2024",
        location: "Santiago",
        category: "Alianzas",
        image: "/placeholder.svg?height=300&width=500",
    },
    {
        title: "Red de emprendedores rurales: primera rueda de negocios 2024",
        excerpt: "Jóvenes emprendedores del campo tuvieron la oportunidad de conectar con compradores, distribuidores y inversionistas en evento organizado por el GNJR.",
        date: "28 Nov 2024",
        location: "Rancagua",
        category: "Emprendimiento",
        image: "/placeholder.svg?height=300&width=500",
    },
    {
        title: "GNJR presenta propuestas para nueva Ley de Fomento Agrícola",
        excerpt: "El gremio participó en audiencia pública presentando propuestas concretas para incluir la perspectiva de la juventud rural en la nueva legislación.",
        date: "20 Nov 2024",
        location: "Valparaíso",
        category: "Políticas Públicas",
        image: "/placeholder.svg?height=300&width=500",
    },
];
